# Coding Tasks - Week 7
Welcome to the Python Programming Exercise Sheet!  
In this exercise sheet, we will cover some of the fundamental concepts in Python programming.  
Topics covered are: NumPy.

___

**DEADLINE**:  19th June until 12:15  
**Your name here**: Sharareh Daneshvar
**Your university mail**: shdaneshvar@uni-osnabrueck.de

___

**Important information**:  
In order to pass this sheet you need to achieve  /  points.  
For the best possible grade you require  /  points, however, since some harder tasks may take a lot of time you don't have to pressure yourself.  
If you complete any three tasks on a sheet you will definitely get a good grade for that sheet.  
Hand in your sheet in studip in the respective folder until the deadline.  
If you receive no email until a few days after submission you will have passed, the sample solution will also be uploaded around then.  
If you receive an email you don't need to worry, you can fail one sheet and also your total points will also be taken into account for the final pass or fail.  

### Task 1 - Array Manipulation (4 points)

Create a Python program that takes a 1D NumPy array of size 10 with random integer values between 1 and 100 (inclusive) and performs the following operations:

- Create the 1D array with the specified size.
- Reshape the array into a 2x5 matrix.
- Transpose the matrix.
- Finally, find the index of the maximum value in the array.

In [14]:
import numpy as np

# Create a 1D array of size 10 with random integer values between 1 and 100
arr = np.random.randint(1, 101, 10)

# Reshape the array into a 2x5 matrix
arr_reshaped = arr.reshape(2,5) #reshape kardan matrix 
# Transpose the matrix
arr_transposed = arr.transpose() #jabejai satro sotun

# Find the index of the maximum value in the array
max_index = arr.argmax() #peida kardane bozorgtarin adad

# Print the original array
print(f"The original array:\n{arr}")

# Print the reshaped array
print(f"The reshaped array:\n{arr_reshaped}")

# Print the transposed array
print(f"The transposed array:\n{arr_transposed}")

# Print the index of the maximum value
print(f"The index of the maximum value:\n{max_index}")


The original array:
[57 35 21 71 18 80 89 60 44 80]
The reshaped array:
[[57 35 21 71 18]
 [80 89 60 44 80]]
The transposed array:
[57 35 21 71 18 80 89 60 44 80]
The index of the maximum value:
6


### Task 2 - Standart Deviation Ratio (SDR) (4 points)

Implement a Python program that calculates the standard deviation ratio (SDR) of a given 1D NumPy array. SDR represents the ratio of the standard deviation of the positive elements to the standard deviation of the negative elements.

- Create a 1D array of 100 random values.
- Split the array into positive and negative elements.
- Calculate the standard deviations of the positive and negative arrays.
- Calculate the standard deviation ratio (SDR).

In [15]:
import numpy as np

# Create a 1D array of 100 random values
arr1 = np.random.randn(100)

# Split the array into positive and negative elements
positive_array = arr1[arr1>=0] #balaye 0 mishe + va ba beraket shart to tain mikoneim 
negative_array = arr1[arr1<0]

# Calculate the standard deviations       #enheraf meyar
positive_std_dev = np.std(positive_array)
negative_std_dev = np.std(negative_array)

# Calculate the standard deviation ratio      #enheraf meyar kol
sdr = np.std(arr1)

# Print the original arrays
print(f"Array:\n{arr1}")

# Print the positive array
print(f"The positive array:\n{positive_array}")

# Print the negative array
print(f"The negative array:\n{negative_array}")

# Print the standard deviation ratio
print(f"Standard Deviation Ratio:\n{sdr}")


Array:
[ 9.49351650e-01  9.67278573e-01  5.06554166e-01  1.37998100e+00
 -6.41331427e-01 -9.25469253e-01  4.14661644e-01  1.26154429e+00
 -4.33909974e-01  1.64792087e+00 -5.44763299e-01 -2.12657068e-01
  2.09090234e-01 -3.55482116e-02  1.24433883e+00  3.23095209e-01
 -1.27822509e-01 -1.39784330e-01  1.43633061e+00 -1.17128030e+00
  1.29285001e-01 -8.62200107e-02 -6.18448696e-02 -3.81988387e-01
 -4.98407788e-01  8.97153111e-01  2.48937398e+00 -5.92410662e-01
  8.56374546e-01  1.33361081e+00  2.26988140e+00 -8.48980169e-01
  7.96579376e-01 -3.74123265e-01  1.55071265e+00 -9.60035321e-01
  1.53486590e-03  1.13121540e+00  2.48466720e-01  2.36041378e+00
 -8.84384138e-01  7.03330328e-01  2.26527685e+00  8.43698407e-01
 -3.45575130e-01  1.08344301e+00  1.14637799e+00 -6.90408654e-01
 -8.64034332e-01 -7.34287399e-01  3.84319116e-01 -2.57371009e+00
  1.91398294e+00 -1.58727951e+00 -7.68832652e-01 -1.26363560e+00
  7.92085863e-01 -1.17104901e-01 -1.19170251e+00  2.27895991e+00
  6.27862821e-01  

### Task 3 - Identity Matrix (3 points)

Create a 5x5 identity matrix where:

- All diagonal elements are equal to 0.
- The rest of the elements should be random integers between 0 and 50 (inclusive).

In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = # Your code here   # matrix hamani: ghotre asli 1 va hameye araye hash 0 ast

# Generate random integers between 0 and 50 (inclusive)
random_integers = # Your code here

# Replace the non-diagonal elements with random integers
identity_matrix[~np.eye(5, dtype=bool)] = random_integers[~np.eye(5, dtype=bool)]

print(identity_matrix)


### Task 4 - Calculate the Euclidean distance between two arrays (2 points)
The Euclidean distance measures the straight-line distance between two points in space. In this task, you will calculate the Euclidean distance between two 1-dimensional arrays using the NumPy library.

**Hint:** To calculate the Euclidean distance between the two arrays, we can use the np.linalg.norm() function. This function calculates the norm, which is a generalized form of the Euclidean distance, of the difference between the arrays:


In [17]:
import numpy as np           # faseleye oghlidosi 

# Create two 1-dimensional arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Calculate the difference between the two arrays
difference = np.square(arr1 - arr2)    #ekhtelaf(menha) ro hesab mikonim va be tavan 2 miresunim

# Calculate the Euclidean distance using the norm function from the linalg module
distance = np.sqrt(np.sum(difference))    #sum baraye zigma bud va sqrt ham mishe jazr

# Print the calculated Euclidean distance
print("Euclidean Distance:", distance)

Euclidean Distance: 5.196152422706632


### Task 5 - Find the Point of Exceeding a Cumulative Sum Threshold (4 points)

Generate a random 1-dimensional array of size 100 with values ranging from 0 to 9. Calculate the cumulative sum of the array and find the index where the cumulative sum exceeds 100 for the first time, then print the index.
Description:
In this task, you will work with a randomly generated 1-dimensional array of numerical values. Your goal is to calculate the cumulative sum of the array, which represents the running total of the values. Then, you need to identify the position in the array where the cumulative sum exceeds a specific threshold.

In [19]:
import numpy as np

# Generate a random 1-dimensional array of size 100 with values ranging from 0 to 9
arr = np.random.randint(0, 10, size=100)

# Calculate the cumulative sum of the array
cumulative_sum = np.cumsum(arr)   #cumsum manzur faravanie tajamoEe ke yani adad ghabli ro jam mikone

# Set the threshold value
threshold = 100      #noghteye 100 be bad

# Find the index where the cumulative sum first exceeds the threshold
index = np.argmax(cumulative_sum > threshold)  #argmax dar indexing karbord dare va dare bozorgtarin araye ro neshun mide
#Print the index where the cumulative sum exceeds the threshold


print("Index where cumulative sum exceeds", threshold, ":", index)


Index where cumulative sum exceeds 100 : 23


### Task 5 - Find the Point of Exceeding a Cumulative Sum Threshold (4 points)

Generate a random 1-dimensional array of size 100 with values ranging from 0 to 9. Calculate the cumulative sum of the array and find the index where the cumulative sum exceeds 100 for the first time, then print the index.
Description:
In this task, you will work with a randomly generated 1-dimensional array of numerical values. Your goal is to calculate the cumulative sum of the array, which represents the running total of the values. Then, you need to identify the position in the array where the cumulative sum exceeds a specific threshold.

### Task 6 - Performing Linear Algebra Operations (3 points)
Description: In this task, you will work with a randomly generated 2-dimensional array and perform linear algebra operations using NumPy. You will calculate the determinant of the array, compute its inverse, and verify that the product of the array and its inverse yields the identity matrix. This task provides an opportunity to explore fundamental linear algebra concepts, such as determinants, matrix inverses, and the properties of the identity matrix, using NumPy.

1. Create a 2-dimensional array with shape (2, 2) and fill it with random integers between 1 and 9.
2. Calculate the determinant of the array.
3. Compute the inverse of the array.
4. Multiply the array by its inverse.
5. Print the final array.

In [21]:
import numpy as np

# Generate a random 2-dimensional array with shape (2, 2) and random integers between 1 and 9
arr = np.random.random.randint(1, 10, size=(2 , 2))

# Calculate the determinant of the array    
determinant = np.linalg.det(arr)  #az numpy jabre khati ra faramikhunim bad az un determinant ro faramikhanim

# Compute the inverse of the array
inverse = np.linalg.inv(arr)

# Multiply the array by its inverse to obtain the identity matrix
identity = 

# Print the resulting identity matrix
print("Identity Matrix:\n", identity)


AttributeError: 'builtin_function_or_method' object has no attribute 'randint'