# Coding Tasks - Week 7
Welcome to the Python Programming Exercise Sheet!  
In this exercise sheet, we will cover some of the fundamental concepts in Python programming.  
Topics covered are: NumPy.

___

**DEADLINE**:  19th June until 12:15  
**Your name here**: Jakob Speck 
**Your university mail**: jspeck@uos.de

___

**Important information**:  
In order to pass this sheet you need to achieve  /  points.  
For the best possible grade you require  /  points, however, since some harder tasks may take a lot of time you don't have to pressure yourself.  
If you complete any three tasks on a sheet you will definitely get a good grade for that sheet.  
Hand in your sheet in studip in the respective folder until the deadline.  
If you receive no email until a few days after submission you will have passed, the sample solution will also be uploaded around then.  
If you receive an email you don't need to worry, you can fail one sheet and also your total points will also be taken into account for the final pass or fail.  

### Task 1 - Array Manipulation (4 points)

Create a Python program that takes a 1D NumPy array of size 10 with random integer values between 1 and 100 (inclusive) and performs the following operations:

- Create the 1D array with the specified size.
- Reshape the array into a 2x5 matrix.
- Transpose the matrix.
- Finally, find the index of the maximum value in the array.

In [5]:
import numpy as np

# Create a 1D array of size 10 with random integer values between 1 and 100
arr = np.random.randint(1, 101, 10)

# Reshape the array into a 2x5 matrix
arr_reshaped = arr.reshape(2,5)

# Transpose the matrix
arr_transposed = arr_reshaped.transpose()

# Find the index of the maximum value in the array
max_index = np.argmax(arr_transposed)

# Print the original array
print(f"The original array:\n{arr}")

# Print the reshaped array
print(f"The reshaped array:\n{arr_reshaped}")

# Print the transposed array
print(f"The transposed array:\n{arr_transposed}")

# Print the index of the maximum value
print(f"The index of the maximum value:\n{max_index}")

The original array:
[60 51 67 10 88 57 26 10 97 92]
The reshaped array:
[[60 51 67 10 88]
 [57 26 10 97 92]]
The transposed array:
[[60 57]
 [51 26]
 [67 10]
 [10 97]
 [88 92]]
The index of the maximum value:
7


### Task 2 - Standart Deviation Ratio (SDR) (4 points)

Implement a Python program that calculates the standard deviation ratio (SDR) of a given 1D NumPy array. SDR represents the ratio of the standard deviation of the positive elements to the standard deviation of the negative elements.

- Create a 1D array of 100 random values.
- Split the array into positive and negative elements.
- Calculate the standard deviations of the positive and negative arrays.
- Calculate the standard deviation ratio (SDR).

In [6]:
import numpy as np

# Create a 1D array of 100 random values
arr1 = np.random.uniform(-50, 50, 100)

# Split the array into positive and negative elements
positive_array = arr1[arr1 >= 0]
negative_array = arr1[arr1 < 0]

# Calculate the standard deviations
positive_std_dev = np.std(positive_array)
negative_std_dev = np.std(negative_array)

# Calculate the standard deviation ratio
sdr = positive_std_dev / negative_std_dev

# Print the original array
print(f"Array:\n{arr1}")

# Print the positive array
print(f"The positive array:\n{positive_array}")

# Print the negative array
print(f"The negative array:\n{negative_array}")

# Print the standard deviation ratio
print(f"Standard Deviation Ratio:\n{sdr}")

# Print the original array
print(f"Array:\n{arr1}")

# Print the positive array
print(f"The positive array:\n{positive_array}")

# Print the negative array
print(f"The negative array:\n{negative_array}")

# Print the standard deviation ratio
print(f"Standard Deviation Ratio:\n{sdr}")


Array:
[ 48.99143597   4.35524396 -30.3099715   -1.05632504   6.62767583
  46.07550687  41.83870526  -1.59321668  28.60273028   9.15438485
   5.48927339  21.39703862 -44.25306442  34.55445161  13.45262677
 -34.31469185 -36.78199639  13.67435892  38.52045956 -23.84294163
 -48.5304406  -23.14911098  35.14083934 -12.94991125 -34.68488598
 -35.62756951 -34.7345139  -28.05134861 -37.73079919 -26.66613021
 -10.71408073 -45.73891823  10.65699407  -5.62427687 -33.97298786
 -13.54488952  21.01841746  25.48769445  33.6994915  -15.9762894
  26.00752053 -28.73755713  11.9357028   42.73433162 -11.06318724
 -41.3251746   41.11189124  -2.00323236  42.37775372 -43.94678867
 -11.29319828  46.3051989   11.47255396  44.79404505  -8.16873265
 -25.08372799  23.79728141 -13.61202788  15.90537933  31.06258693
   5.17554381 -13.8923193    7.27250734 -15.88654572 -22.16746766
  44.24407499  22.14149171 -36.06985191 -23.82844701 -20.35441732
  18.3271442   27.95422527  -5.57692142   0.57486713  10.17114264
  37

### Task 3 - Identity Matrix (3 points)

Create a 5x5 identity matrix where:

- All diagonal elements are equal to 0.
- The rest of the elements should be random integers between 0 and 50 (inclusive).

In [ ]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.zeros((5,5))

# Generate random integers between 0 and 50 (inclusive)
random_integers = np.random.randint(0, 51, (5,5))

# Replace the non-diagonal elements with random integers
identity_matrix[~np.eye(5, dtype=bool)] = random_integers[~np.eye(5, dtype=bool)]

print(identity_matrix)

### Task 4 - Calculate the Euclidean distance between two arrays (2 points)
The Euclidean distance measures the straight-line distance between two points in space. In this task, you will calculate the Euclidean distance between two 1-dimensional arrays using the NumPy library.

**Hint:** To calculate the Euclidean distance between the two arrays, we can use the np.linalg.norm() function. This function calculates the norm, which is a generalized form of the Euclidean distance, of the difference between the arrays:


In [7]:
import numpy as np

# Create two 1-dimensional arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Calculate the difference between the two arrays
difference = arr2 - arr1

# Calculate the Euclidean distance using the norm function from the linalg module
distance = np.linalg.norm(difference)

# Print the calculated Euclidean distance
print("Euclidean Distance:", distance)

Euclidean Distance: 5.196152422706632


### Task 5 - Find the Point of Exceeding a Cumulative Sum Threshold (4 points)

Generate a random 1-dimensional array of size 100 with values ranging from 0 to 9. Calculate the cumulative sum of the array and find the index where the cumulative sum exceeds 100 for the first time, then print the index.
Description:
In this task, you will work with a randomly generated 1-dimensional array of numerical values. Your goal is to calculate the cumulative sum of the array, which represents the running total of the values. Then, you need to identify the position in the array where the cumulative sum exceeds a specific threshold.

In [8]:
import numpy as np

# Generate a random 1-dimensional array of size 100 with values ranging from 0 to 9
arr = np.random.randint(0, 10, size=100)

# Calculate the cumulative sum of the array
cumulative_sum = np.cumsum(arr)

# Set the threshold value
threshold = 100

# Find the index where the cumulative sum first exceeds the threshold
index = np.argmax(cumulative_sum > threshold)

# Print the index where the cumulative sum exceeds the threshold
print("Index where cumulative sum exceeds", threshold, ":", index)



[  3  10  14  14  21  25  26  29  29  35  44  46  51  53  57  63  66  66
  68  77  81  90  93  93 100 105 109 115 115 120 120 129 134 139 148 157
 160 160 169 169 174 180 186 195 201 208 216 217 224 232 233 242 245 247
 247 253 254 258 260 263 263 270 277 282 289 296 297 303 308 309 318 322
 328 335 335 342 351 358 361 366 368 374 379 381 381 384 385 394 396 403
 411 420 426 426 430 439 442 449 451 452]
Index where cumulative sum exceeds 100 : 25


### Task 6 - Performing Linear Algebra Operations (3 points)
Description: In this task, you will work with a randomly generated 2-dimensional array and perform linear algebra operations using NumPy. You will calculate the determinant of the array, compute its inverse, and verify that the product of the array and its inverse yields the identity matrix. This task provides an opportunity to explore fundamental linear algebra concepts, such as determinants, matrix inverses, and the properties of the identity matrix, using NumPy.

1. Create a 2-dimensional array with shape (2, 2) and fill it with random integers between 1 and 9.
2. Calculate the determinant of the array.
3. Compute the inverse of the array.
4. Multiply the array by its inverse.
5. Print the final array.

In [15]:
import numpy as np

# Generate a random 2-dimensional array with shape (2, 2) and random integers between 1 and 9
arr = np.random.randint(1, 10, size=(2,2))

# Calculate the determinant of the array
determinant = np.linalg.det(arr)

# Compute the inverse of the array
inverse = np.linalg.inv(arr)

# Multiply the array by its inverse to obtain the identity matrix
identity = np.dot(arr, inverse)

# Print the resulting identity matrix
print("Identity Matrix:\n", identity)


Identity Matrix:
 [[1.00000000e+00 2.22044605e-16]
 [1.11022302e-16 1.00000000e+00]]
